var places = [
  {
    name: [
      "Kingston",
      "Portmore",
      "Spanish Town",
      "Montego Bay",
      "May Pen",
      "Mandeville",
      "Old Harbour",
      "Savanna-la-Mar",
      "Linstead",
      "Port Antonio",
    ],
    country: "Jamaica",
    timezoneHours: -5,
    timezoneMinutes: 0,
    DST: false,
  },
  /* American States */
  {
    name: ["Huntsville", "Birmingham", "Montgomery", "Mobile", "Tuscaloosa"],
    country: "Alabama USA",
    timezoneHours: -5,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Anchorage", "Juneau", "Fairbanks", "Wasilla", "Sitka"],
    country: "Alaska USA",
    timezoneHours: -8,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"],
    country: "Arizona USA",
    timezoneHours: -6,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale"],
    country: "Arkansas USA",
    timezoneHours: -5,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno"],
    country: "California USA",
    timezoneHours: -7,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood"],
    country: "Colorado USA",
    timezoneHours: -6,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg"],
    country: "Florida USA",
    timezoneHours: -5,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
    country: "Maine USA",
    timezoneHours: -4,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Baltimore", "Frederick", "Gaithersburg", "Rockville", "Bowie"],
    country: "Maryland USA",
    timezoneHours: -4,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Jackson", "Gulfport", "Southhaven", "Biloxi", "Hattiesburg"],
    country: "Mississippi USA",
    timezoneHours: -5,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Las Vegas", "Henderson", "Reno", "Sparks", "Carson City"],
    country: "Nevada USA",
    timezoneHours: -7,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["New York", "Buffalo", "Rochester", "Yonkers", "Syracuse"],
    country: "New York USA",
    timezoneHours: -4,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"],
    country: "Texas USA",
    timezoneHours: -5,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
    country: "Washington USA",
    timezoneHours: -7,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Charleston", "Huntington", "Morgantown", "Parkersburg"],
    country: "West Virginia USA",
    timezoneHours: -4,
    timezoneMinutes: 0,
    DST: true,
  },
  //European Countries
  {
    name: ["Differdange", "Luxembourg City", "Esch-sur-Alzette", "Dudelange"],
    country: "Luxembourg",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: [
      "Leeds",
      "London",
      "Manchester",
      "Birmingham",
      "Hull",
      "Liverpool",
      "Bristol",
      "Sheffield",
      "Bradford",
      "Leicester",
    ],
    country: "England",
    timezoneHours: 1,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: [
      "Strasbourg",
      "Lyon",
      "Paris",
      "Toulouse",
      "Lille",
      "Montpellier",
      "Nantes",
      "Rennes",
      "Le Havre",
      "Reims",
    ],
    country: "France",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: [
      "Graz",
      "Vienna",
      "Linz",
      "Salzburg",
      "Innsbruck",
      "Weiner Neustadt",
      "Feldkirch",
      "Bregenz",
      "Klosterneuburg",
      "Baden",
    ],
    country: "Austria",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: [
      "Antwerp",
      "Ghent",
      "Charleroi",
      "Liege",
      "Brussels",
      "Schaerbeek",
      "Bruges",
      "Namur",
      "Leuven",
    ],
    country: "Belgium",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Velika Gorica"],
    country: "Croatia",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Copenhagen", "Odense", "Frederiksberg", "Aarhus", "Aalborg"],
    country: "Denmark",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-jarve"],
    country: "Estonia",
    timezoneHours: 3,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
    country: "Finland",
    timezoneHours: 3,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: [
      "Dusseldorf",
      "Leipzig",
      "Frankfurt",
      "Stuttgart",
      "Cologne",
      "Hamburg",
      "Essen",
      "Dresden",
      "Bremen",
      "Berlin",
    ],
    country: "Germany",
    timezoneHours: 2,
    timezoneMinutes: 0,
    DST: true,
  },
  // Australian States
  {
    name: ["Melbourne"],
    country: "Victoria Australia",
    timezoneHours: 10,
    timezoneMinutes: 0,
    DST: true,
  },
  {
    name: ["Adelaide"],
    country: "South Australia",
    timezoneHours: 9,
    timezoneMinutes: 30,
    DST: true,
  },
];
